### ISSUE TITLE
Coding Task - Plot the deltas (such that non zero values are white and see the distribution)

### ISSUE THREAD

**Issue by suman1209** [suman1209/robotics_dataset_compression#1]
**Task description**

In the TensorStorage class, there are methods to find the delta between two images.
In this task, if you try to plot the deltas, they are going to appear like a full black image, we want to write a code that can enhance the non zero pixels such that for each channel, we can visualise the where the non - zero values are found.

**Todos**
1. Create a seperate branch
2. In the TensorStorage class, add a method called **visualize_enhanced_delta** which takes in two images and and the channel and outputs the required enhanced delta image.

**deliverables**
1.  clean working code
2. results of some examples (please add it as a reply to this task and also add it to our meeting [notes documentation](https://docs.google.com/document/d/1GEf8tKDDW-6mNyY3pii27Ya57PSSvnLDUFbutmY8BC8/edit)

**Comment by ASBJ021** [comment]
Implemented enhanced delta image plot.

**Comment by ASBJ021** [comment]
Implemented enlarging non zero delta values and plotting them
