### ISSUE TITLE
how png works

### ISSUE THREAD

**Issue by suman1209** [suman1209/robotics_dataset_compression#17]

**Comment by ASBJ021** [comment]
https://medium.com/@duhroach/how-png-works-f1174e3cc7b7

**Comment by ASBJ021** [comment]
https://youtu.be/EFUYNoFRHQI?si=sCuVMKX_j3LzQ4oE

![Uploading Screenshot 2024-09-27 at 9.46.37 AM.png…]()

**Comment by suman1209** [comment]
Is there a standard compression ratio stated for PNG somewhere?

**Comment by ASBJ021** [comment]
t the PNG file size can be between 20% to 50% of the original image size in uncompressed form

**Comment by suman1209** [comment]
> the PNG file size can be between 20% to 50% of the original image size in uncompressed form

oh thats a good compression, but it compresses image by image right, what we do differently is try to use information from sequential images looking for compressing opprotunities

**Comment by ASBJ021** [comment]
Yes. One image at a time. it compresses all channels differently, and row by row. That's what I understood.

**Comment by ASBJ021** [comment]
This gives overview of structure on png:
https://www.quora.com/How-is-PNG-data-encoded

**Comment by ASBJ021** [comment]
This is same a png but faster:
https://qoiformat.org/
