### ISSUE TITLE
Evaluation with standard compression algorithms

### ISSUE THREAD

**Issue by suman1209** [suman1209/robotics_dataset_compression#4]
**Task description**

This task is fto evaluate our approach with standard video encoding techniques.

**Todos**
1. Look for standard video compression techniques used and see what the compression we can get
2. compare the methods with our approach

**deliverables**
1. codes for implementations
2. a comparison table (add the table as a reply here and also add it to the meeting [notes documentation](https://docs.google.com/document/d/1GEf8tKDDW-6mNyY3pii27Ya57PSSvnLDUFbutmY8BC8/edit)

**Comment by suman1209** [comment]
https://siipo.la/blog/whats-the-best-lossless-image-format-comparing-png-webp-avif-and-jpeg-xl
for reference

**Comment by billy0705** [comment]
Lossless Video Compression:

1. [Advanced Video Coding AVC / H.264 / MPEG-4 Part 10](http://ip.hhi.de/imagecom_G1/assets/pdfs/csvt_overview_0305.pdf)
2. [High Efficiency Video Coding HEVC / H.265 / MPEG-H Part 2](https://iphome.hhi.de/wiegand/assets/pdfs/2012_12_IEEE-HEVC-Overview.pdf)
3. [Versatile Video Coding VVC / H.266 / MPEG-I Part 3](https://ieeexplore.ieee.org/document/9503377)

**Comment by Priyam1204** [comment]
[img2vid.txt](https://github.com/user-attachments/files/16711301/img2vid.txt)

**Comment by suman1209** [comment]
We need a summary of the compression ratio and compression speed for each algorithm.

**Comment by billy0705** [comment]
Using the ffmpeg to convert images to video with different format.
https://trac.ffmpeg.org/wiki/Encode/H.264#LosslessH.264
https://trac.ffmpeg.org/wiki/Encode/H.265#Losslessencoding

Result:
raw_image_size= 47222049
h264_slow_size= 16346421
h264_fast_size= 29366211
h265_slow_size= 51568709
h265_fast_size= 64834478

**Comment by billy0705** [comment]
Result in kB:
png_image_size= 17472.61621
h264_slow_size=  6160.37305
h264_fast_size=   7775.41308
h265_slow_size= 10662.82715
h265_fast_size= 11879349

**Comment by billy0705** [comment]
https://www.vcodex.com/an-overview-of-h264-advanced-video-coding
H264 algorithm
