### ISSUE TITLE
Research tasks

### ISSUE THREAD

**Issue by suman1209** [suman1209/robotics_dataset_compression#5]
**Task description**

This task is to research if there is any encoding schemes suitable for sequential video data

**Todos:**

1. select one or two algorithms from research papers
2.  try out a prototype and compare the final decompressed size

**Comment by suman1209** [comment]
found this

https://www.timescale.com/blog/time-series-compression-algorithms-explained/

**Comment by ASBJ021** [comment]
I found this github repo for AI based compression. Its just for reference .
https://interdigitalinc.github.io/CompressAI/zoo.html

**Comment by ASBJ021** [comment]
https://yasoob.me/posts/understanding-and-writing-jpeg-decoder-in-python/
