### ISSUE TITLE
Coding Task - Results table generation

### ISSUE THREAD

**Issue by suman1209** [suman1209/robotics_dataset_compression#7]
**Task description**

This task is to write a small program to automatically compare the algorithms that we implemented and create a table of results.

**Todos**

**deliverables**
1. codes for implementations
2. a comparison table output from the program
    e.g. a table with the following labels

    |Method | Compression Speed | Decompression Speed | Compression factor|

**Comment by suman1209** [comment]
Lets use the first 100 images for getting the results

**Comment by ASBJ021** [comment]
Ok will do that.

**Comment by ASBJ021** [comment]
Created a PR for the same
